"""Transport-independent operation vocabulary."""

OPERATIONS = {
    "knowledge_list": ("list", "Browse notes and child namespaces (ordinary directories). Depth 1 lists immediate children; use pages for large listings."),
    "knowledge_search": ("search", "Full-text search within explicit namespaces. recursive=true includes descendants; root '/' selects the base. Follow next_cursor even when results are empty: scans are bounded and has_more means search is incomplete. After traversal, changed native totals restart the cursor at the first page; deduplicate repeated identities. index_changed remains set and even an exhausted result is then partial. Stable totals do not prove snapshot consistency. retrieval_mode is text (default), semantic, or hybrid; the latter two require backend support. No semantic-search claim."),
    "knowledge_read": ("read", "Read an exact returned identifier or directory-qualified wiki target. An omitted .md suffix is accepted only for the matching physical note; bare-title guesses remain unsupported. Content is paged by character offset; follow next_offset before editing truncated notes. For governed mode='inspect', include_history=false returns current fields without events; the default includes full validated history."),
    "knowledge_create": ("create", "Write supplied Markdown and optional metadata into an explicit namespace. Creates parent directories as needed and never silently overwrites. Returns the backend-assigned identifier and a verified change receipt; no template or relationship is inserted."),
    "knowledge_edit": ("edit", "Change exactly one current body passage and/or merge metadata on an existing note. Pass both find_text and replacement for a body edit. Returns a verified change receipt. Read back after an uncertain result before retrying."),
    "knowledge_revise": ("revise", "Apply ordered exact replacements to one ordinary note after its complete-body SHA-256 matches expected_content_sha256. preview=true computes the resulting body without mutation; successful writes return a verified grouped change receipt."),
    "knowledge_inspect_collection": ("inspect_collection", "Inspect one explicit namespace through a live bounded scan. Returns ordinary-note identities, complete-body hashes, omissions, continuation, and page-scoped exact-duplicate candidates only. After traversal, changed native totals restart next_cursor at the first page; deduplicate repeated identities. exhausted=true means traversal ended; partial=true or index_changed=true still means the inventory is incomplete. No semantic quality or snapshot-consistency claim."),
    "knowledge_context": ("context", "Read multiple selected notes under one total body-character budget, using either a namespace page or exact identifiers. Returns structured notes, omissions and continuation. Links are not followed implicitly. mode=inspect returns prose and current metadata without history or a reuse check; use knowledge_read for a complete record when its preview is truncated."),
    "knowledge_move": ("move", "Move an exact note or namespace through Basic Memory. Set is_namespace=true for a directory move. Destination is a relative path; inspect the returned receipt and addresses, and reconcile uncertain results before retrying."),
    "knowledge_related": ("related", "Read a known note together with its linked neighbors in explicit namespaces, including notes that link to it. Use this for orientation across related topics without separate reads; depth=2 can reach a neighbor's linked topics. When the task permits cross-system context, namespaces=['/'] includes the accessible base; narrower namespaces exclude links outside them. mode=inspect returns prose and current metadata without history or a reuse check; use knowledge_read for a complete record when its preview is truncated."),
    "knowledge_record_maintain": ("record_maintain", "Mark affected dependent records for review in a bounded namespace inventory. Reports partial progress and safe replay."),
    "knowledge_record_remove": ("record_remove", "Remove one exact governed record at an expected revision. Reports backend deletion and bounded index-removal evidence; does not erase backups."),
    "knowledge_record_create": ("record_create", "Create one governed claim with evidence, scope, and revision history. record.record_id is a bare name without .md; put directories in namespace. Returns committed revision and receipt. Set include_history=false to omit record snapshots from this response; full history remains available through knowledge_read(mode=inspect)."),
    "knowledge_record_transition": ("record_transition", "Apply a lifecycle transition with expected_revision and a unique operation_id. For action='supersede', use changes={successor_identifier, successor_revision}; the stored successor must be supported in the same namespace and scope. Do not copy its full record. For action='revise', changes accepts only claim, replacements, scope, observations, evidence, verification, depends_on, and mirror_observations. Use claim or replacements=[{find_text, replacement}], never both. Exact selections must be unique and disjoint. changes.evidence is an object keyed by evidence ID, not a list. To update declared whole-claim mirrors atomically, supply mirror_observations=[existing_observation_id] with claim or replacements, never with observations. Each selected statement must exactly match the current whole claim; unselected statements and evidence bindings remain unchanged. Review observation statements as well as their evidence IDs; update changes.observations in the same revision when either changes. Supplied verification needs record_revision, verified_at, verifier, outcome, and evidence_ids. Changed claims need fresh verification to remain supported: bind verification.record_revision to expected_revision+1. timestamp and verification.verified_at require six fractional digits and Z, for example 2026-01-01T12:00:00.000001Z. Verification must be newer than the prior verification and no later than timestamp. Inspect uncertain results before retrying. Set include_history=false to omit record snapshots from this response while retaining the complete receipt and replay fields."),
}
